// This configuration is automatically generated by Firebase Studio.
// Do not edit this file manually.
import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyDDRF22vXkiHT0T1NLWuqfj66xJ7TaPsDo",
  appId: "1:344820186473:web:3d53cee9849eb2ef9211f8",
  authDomain: "cadastro-3c63f-e1d52.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "344820186473",
  projectId: "cadastro-3c63f",
};
